docker run -d --name broker  -p 9092:9092 `
    -e KAFKA_CFG_NODE_ID=1 `
    -e KAFKA_CFG_PROCESS_ROLES=broker,controller `
    -e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER `
    -e KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 `
    -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 `
    -e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 `
    bitnami/kafka:latest